-- Generated by backend/scripts/build-seed.mjs from supabase/seed-data/*.json. Do not edit by hand.
insert into public.grades (id, name, sort) values
  (9, 'Grade 9', 1),
  (10, 'Grade 10', 2),
  (11, 'Grade 11', 3),
  (12, 'Grade 12', 4)
on conflict (id) do update set name = excluded.name, sort = excluded.sort;
insert into public.packages (id, grade_id, name, tier, description, features, price_etb, duration_days, includes_videos, includes_qbank, includes_tests, is_active, sort) values
  ('591fb1da-81ca-48fb-8995-63ed097bcb2c', 9, 'Basic', 'basic', 'Every Grade 9 video lesson and the full question bank.', array['All video lessons', 'Full question bank', 'Step-by-step explanations']::text[], 299, 180, true, true, false, true, 1),
  ('06682c75-e673-4c0e-90f5-041954385888', 9, 'Premium', 'premium', 'Everything in Basic plus mock and unit tests for a full year.', array['Everything in Basic', 'Timed mock & unit tests', 'Detailed results and review']::text[], 549, 365, true, true, true, true, 2),
  ('76e3e1e7-47c7-41ee-9234-28d8d10ea130', 10, 'Basic', 'basic', 'Every Grade 10 video lesson and the full question bank.', array['All video lessons', 'Full question bank', 'Step-by-step explanations']::text[], 349, 180, true, true, false, true, 1),
  ('f7284683-6ef0-4ad0-ae14-50d288dcf1c8', 10, 'Premium', 'premium', 'Everything in Basic plus mock and unit tests for a full year.', array['Everything in Basic', 'Timed mock & unit tests', 'Detailed results and review']::text[], 649, 365, true, true, true, true, 2),
  ('ac65fc15-6358-449e-8062-27721ac9703b', 11, 'Basic', 'basic', 'Every Grade 11 video lesson and the full question bank.', array['All video lessons', 'Full question bank', 'Step-by-step explanations']::text[], 399, 180, true, true, false, true, 1),
  ('a25d0679-47af-4f6a-aa00-d9bfc94d32d9', 11, 'Premium', 'premium', 'Everything in Basic plus mock and unit tests for a full year.', array['Everything in Basic', 'Timed mock & unit tests', 'Detailed results and review']::text[], 749, 365, true, true, true, true, 2),
  ('f1e5597c-e9f3-42f8-b69c-2f8253090917', 12, 'Basic', 'basic', 'Every Grade 12 video lesson and the full question bank.', array['All video lessons', 'Full question bank', 'Step-by-step explanations']::text[], 499, 180, true, true, false, true, 1),
  ('a995aefc-904e-46ea-b0a5-3b96b10848e6', 12, 'Premium', 'premium', 'Everything in Basic plus past national exams, mock and unit tests for a full year.', array['Everything in Basic', 'Past national exam papers', 'Timed mock & unit tests', 'Detailed results and review']::text[], 999, 365, true, true, true, true, 2)
on conflict (id) do update set grade_id = excluded.grade_id, name = excluded.name, tier = excluded.tier, description = excluded.description, features = excluded.features, price_etb = excluded.price_etb, duration_days = excluded.duration_days, includes_videos = excluded.includes_videos, includes_qbank = excluded.includes_qbank, includes_tests = excluded.includes_tests, is_active = excluded.is_active, sort = excluded.sort;
